[package]
name = "orc-format"
version = "0.1.0"
authors = ["Sean Gallagher <stgallag@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.16.2"

[build-dependencies]
protobuf-codegen-pure = "2.16.2"