#[macro_use] extern crate maplit;
#[macro_use] extern crate hex_literal;
#[macro_use] extern crate serde_json;
mod errors;
mod nibble;
mod schemata;
mod toc;
mod codecs;
#[cfg(test)] mod tests;

pub use toc::ORCFile;
pub use schemata::Column;

/// Autogenerated messages from the ORC reference implementation's `protobuf` definition
pub mod messages {
    include!(concat!(env!("OUT_DIR"), "/orc.proto.rs"));
}